// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO9OODmnkNHqMduducWjS1iNbv_BSyre8',
    appId: '1:667865093938:web:7a67ea5394e7fbef00e92b',
    messagingSenderId: '667865093938',
    projectId: 'crypter-a65b8',
    authDomain: 'crypter-a65b8.firebaseapp.com',
    storageBucket: 'crypter-a65b8.firebasestorage.app',
    measurementId: 'G-1P5LB6TWLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXn9uPkI9uTmpuIHnFlNuVNHpKIJ0b0oI',
    appId: '1:667865093938:android:29a85ec1c15072f400e92b',
    messagingSenderId: '667865093938',
    projectId: 'crypter-a65b8',
    storageBucket: 'crypter-a65b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqU7rbPYiz6WW1TSLtbyYy8GtXBiRXVZw',
    appId: '1:667865093938:ios:1a6dc0c58a2bdf5b00e92b',
    messagingSenderId: '667865093938',
    projectId: 'crypter-a65b8',
    storageBucket: 'crypter-a65b8.firebasestorage.app',
    iosBundleId: 'com.example.crypter',
  );
}
