# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Building the app for simulator (without signing)"
  lane :build_for_simulator do
    sh("flutter build ios --no-codesign --simulator --debug")

    zip(
      path: "./build/ios/Debug-iphonesimulator/Runner.app",
      output_path: "./build/ios/archives/iphonesimulator/Crypter-Simulator.zip"
    )
  end
end
