name: Android deployment to App Distribution

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  android_build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    timeout-minutes: 60

    env:
      ENVIRONMENT: ${{ inputs.environment }}
      PLATFORM: ${{ inputs.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Cache Gradle files
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles(
              'android/build.gradle',
              'android/app/build.gradle',
              'android/gradle/wrapper/gradle-wrapper.properties'
            ) }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: |
          flutter build ${{ vars.ANDROID_BUILD_TYPE }} \
          -t lib/main.dart \
          --build-name ${{ env.VERSION }} \
          --build-number ${{ env.BUILD_NUMBER }}

      - name: Install Firebase CLI
        uses: ./.github/actions/install-firebase-cli

      - name: Authenticate to Google Cloud via a service account key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Distribute to App Distribution
        run: |
          firebase appdistribution:distribute ${{ vars.ANDROID_BUILD_OUTPUT_PATH }} \
          --app ${{ vars.FIREBASE_ANDROID_APP_ID }} \
          --release-notes "${{ github.ref_name }} ${{ env.SHORT_SHA }}. ${{ env.COMMIT_MESSAGE }}" \
          --groups testers

      - name: Add tag to commit
        uses: ./.github/actions/add-tag
